#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
source $DIR/conf

$DIR/compile

cd $VMROOT_DIR

if [ "$1" = "-v" ]; then
  tmux split-window "sys161 -w kernel"
else
  tmux split-window -h "sys161 -w kernel"
fi
os161-gdb kernel -ex="connect"
